"""``python -m athanore.cli``: the CLI without the console script.

``[project.scripts]`` in ``pyproject.toml`` installs ``athanore`` and
that is what an operator runs. This module is the same entry point
reached through the interpreter, which is what a test that spawns the CLI
as a subprocess uses: it depends on the package being importable rather
than on a script having been regenerated by the last install, so a
checkout that was synced a moment ago and one that was not behave the
same.
"""

from athanore.cli import main

raise SystemExit(main())
