/**
 * theme.css is generated by `web/scripts/gen-theme.mjs` and never
 * hand-edited (AGENTS.md §Conventions). These tests are what makes that
 * true: they run in `pnpm test`, which is a step of `./scripts/test.sh`
 * and of CI's `web` job, so an edit to either file that was not followed
 * by `pnpm gen:theme` turns the gate red.
 */
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { compile } from 'tailwindcss'
import { describe, expect, it } from 'vitest'

const WEB = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const GENERATOR = resolve(WEB, 'scripts/gen-theme.mjs')
const SOURCE = resolve(WEB, '../docs/v1/design/nocturne.css')
const THEME = resolve(WEB, 'src/styles/theme.css')
const ENTRY = resolve(WEB, 'src/index.css')

const nocturne = readFileSync(SOURCE, 'utf8')
const theme = readFileSync(THEME, 'utf8')

/** Every `--name: value;` Nocturne declares inside a `:root` block. */
function nocturneTokens(): [string, string][] {
  const declarations: [string, string][] = []
  for (const line of nocturne.split('\n')) {
    const match = /^\s*(--[a-z0-9-]+)\s*:\s*([^;]+?)\s*;/i.exec(line)
    if (match?.[1] && match[2]) declarations.push([match[1], match[2]])
  }
  return declarations
}

/** Every `@utility NAME { ... }` the generated stylesheet declares. */
function generatedUtilities(): Map<string, string[]> {
  const utilities = new Map<string, string[]>()
  for (const [, name, body] of theme.matchAll(/@utility ([a-z0-9-]+) \{([^}]*)\}/g)) {
    utilities.set(name ?? '', properties(body ?? ''))
  }
  return utilities
}

/** The property names of a declaration block, `font-size: 11px;` → `font-size`. */
function properties(block: string): string[] {
  return block
    .split(';')
    .map((declaration) => declaration.slice(0, declaration.indexOf(':')).trim())
    .filter((property) => property.length > 0)
}

/**
 * Where a CSS `@import` points, with the `style` condition Tailwind
 * resolves stylesheets under — `tailwindcss` and `tw-animate-css` both
 * publish their CSS there and their JavaScript (or nothing) to
 * `require`, so `require.resolve` alone lands on the wrong file.
 */
function resolveStylesheet(id: string, base: string): string {
  if (id.startsWith('.')) return resolve(base, id)
  const require_ = createRequire(join(base, 'entry.css'))
  const parts = id.split('/')
  const pkg = id.startsWith('@') ? parts.slice(0, 2).join('/') : (parts[0] ?? id)
  if (id !== pkg) return require_.resolve(id)
  for (const directory of require_.resolve.paths(pkg) ?? []) {
    const manifest = join(directory, pkg, 'package.json')
    if (!existsSync(manifest)) continue
    const json: {
      exports?: { '.'?: { style?: string } }
      style?: string
      main?: string
    } = JSON.parse(readFileSync(manifest, 'utf8'))
    const style = json.exports?.['.']?.style ?? json.style ?? json.main
    if (typeof style === 'string' && style.endsWith('.css')) {
      return join(directory, pkg, style)
    }
    break
  }
  return require_.resolve(id)
}

/**
 * `class` → the properties Tailwind actually paints it with, compiled
 * from `src/index.css` — the stylesheet the app ships, theme.css
 * included, in its import order.
 *
 * theme.css on its own is only half the cascade: Tailwind derives a
 * colour utility from every `--color-*` key of `@theme inline`, so a
 * `@utility` whose name matches one lands in the same class with an
 * extra `color`, and jsdom cannot see it (it does not resolve Tailwind
 * at all). This compiles the sheet and reads the rules back out.
 */
async function compiledProperties(
  candidates: string[],
): Promise<Map<string, string[]>> {
  const compiler = await compile(readFileSync(ENTRY, 'utf8'), {
    base: dirname(ENTRY),
    loadStylesheet: async (id, base) => {
      const path = resolveStylesheet(id, base)
      return { path, base: dirname(path), content: readFileSync(path, 'utf8') }
    },
    loadModule: async (id) => {
      throw new Error(`${ENTRY} loads no plugin or config, but asked for ${id}`)
    },
  })
  return selectorProperties(compiler.build(candidates))
}

/**
 * Every `selector → property` pair of a compiled stylesheet, nesting
 * included: a declaration inside an `@supports` or an `@media` belongs
 * to the nearest selector above it, which is how `.bg-chrome`'s
 * `color-mix` fallback and the reduced-motion guard are counted.
 */
function selectorProperties(css: string): Map<string, string[]> {
  const found = new Map<string, string[]>()
  const stack: string[] = []
  let buffer = ''

  const flush = () => {
    const text = buffer.trim()
    buffer = ''
    if (!text.includes(':') || text.startsWith('@')) return
    const property = text.slice(0, text.indexOf(':')).trim()
    const owner = [...stack].reverse().find((prelude) => !prelude.startsWith('@'))
    for (const selector of owner?.split(',') ?? []) {
      const key = selector.trim()
      found.set(key, [...(found.get(key) ?? []), property])
    }
  }

  for (const character of css) {
    if (character === '{') {
      stack.push(buffer.trim())
      buffer = ''
    } else if (character === ';') {
      flush()
    } else if (character === '}') {
      flush()
      stack.pop()
    } else {
      buffer += character
    }
  }
  return found
}

describe('theme.css', () => {
  it('is what gen-theme.mjs builds from nocturne.css', () => {
    const check = spawnSync(process.execPath, [GENERATOR, '--check'], {
      encoding: 'utf8',
    })
    expect(check.error).toBeUndefined()
    expect(`${check.stdout}${check.stderr}`.trim()).toBe('')
    expect(check.status).toBe(0)
  })

  it('carries every --color-, --space-, --shadow- and --ath- token', () => {
    const copied = nocturneTokens().filter(([name]) =>
      ['--color-', '--space-', '--shadow-', '--ath-'].some((p) => name.startsWith(p)),
    )
    expect(copied.length).toBeGreaterThan(40)
    for (const [name, value] of copied) {
      expect(theme, `${name} is missing or changed`).toContain(`${name}: ${value};`)
    }
  })

  it('does not copy the token families the app does not use', () => {
    // --radius-* and --font-heading/--font-body are Nocturne's document
    // defaults for a document, not for a terminal. The app declares its
    // own radius and its one mono face further down the file instead
    // (10 §Design system, D71), so Nocturne's values must not appear.
    for (const [name, value] of nocturneTokens()) {
      const copied = ['--color-', '--space-', '--shadow-', '--ath-'].some((p) =>
        name.startsWith(p),
      )
      if (!copied) {
        expect(theme, `${name} should not have been copied`).not.toContain(
          `${name}: ${value};`,
        )
      }
    }
  })

  it('maps every shadcn variable of 10 §Tokens → shadcn', () => {
    const mapping: [string, string][] = [
      ['--background', 'var(--color-bg)'],
      ['--card', 'var(--color-surface)'],
      ['--popover', 'var(--color-surface)'],
      ['--secondary', 'var(--color-surface)'],
      ['--foreground', 'var(--color-text)'],
      ['--muted-foreground', 'var(--color-neutral-500)'],
      ['--muted', 'var(--color-neutral-900)'],
      ['--border', 'var(--color-neutral-800)'],
      ['--input', 'var(--color-neutral-800)'],
      ['--primary', 'var(--color-accent)'],
      ['--primary-foreground', 'var(--color-accent-200)'],
      ['--accent', 'color-mix(in srgb, var(--color-accent) 16%, transparent)'],
      ['--destructive', 'var(--ath-status-fail)'],
      ['--ring', 'var(--color-accent)'],
      ['--chart-1', 'var(--color-accent)'],
      ['--chart-2', 'var(--color-accent-700)'],
      ['--chart-3', 'var(--color-accent-2-400)'],
    ]
    for (const [name, value] of mapping) {
      expect(theme, `${name} is not mapped onto ${value}`).toContain(
        `${name}: ${value};`,
      )
    }
  })

  it("leaves the radius at Nocturne's 8 px (D71)", () => {
    expect(theme).toContain('--radius: 8px;')
    expect(theme).not.toContain('--radius: var(--ath-radius)')
  })

  it('exposes the shadcn variables to Tailwind and no undefined ones', () => {
    const inline = /@theme inline \{([\s\S]*?)\n\}/.exec(theme)?.[1]
    expect(inline).toBeDefined()
    expect(inline).toContain('--color-background: var(--background);')
    expect(inline).toContain("--font-mono: 'JetBrains Mono Variable', var(--ath-font-mono);")
    // Roles 10 does not define would resolve to nothing at runtime.
    expect(inline).not.toContain('--color-sidebar')
    expect(inline).not.toContain('--color-chart-4')
    expect(inline).not.toContain('--color-chart-5')
  })

  it('sets the base of the app type scale, and the chooser\u2019s four steps', () => {
    // The base itself is the token; `text-body` is `1rem`, which is the
    // base by definition (21 §Type scale).
    expect(theme).toContain('font-size: var(--ath-font-size);')
    expect(theme).toContain('@utility text-body { font-size: 1rem; }')

    // `default` is the absence of the attribute, so there are three
    // rules and four steps (D195).
    const steps: [string, string][] = [
      ['small', '11'],
      ['large', '13.5'],
      ['xlarge', '15'],
    ]
    for (const [step, numerator] of steps) {
      expect(theme).toContain(`html[data-font-size='${step}'] {`)
      expect(theme).toContain(
        `font-size: calc(var(--ath-font-size) * ${numerator} / 12);`,
      )
    }
    expect(theme).not.toContain("html[data-font-size='default']")
  })

  it('holds the density still while the base moves (D195, D199)', () => {
    // Tailwind's own spacing scale is 0.25rem a step, which would grow
    // with the base the chooser sets and take every padding and gap in
    // the app with it. 3 px is what it already resolves to at 12 px.
    expect(theme).toContain('--spacing: 3px;')
  })

  it('paints every status colour of 10 §Status colours', () => {
    const statuses: [string, string][] = [
      ['ok', 'var(--ath-status-ok)'], // completed / done
      ['active', 'var(--ath-status-active)'], // running / in_progress
      ['gate', 'var(--ath-status-gate)'], // waiting on a human
      ['queued', 'var(--ath-status-queued)'], // queued / ready
      ['fail', 'var(--ath-status-fail)'], // failed / dead_letter
      ['muted', 'var(--ath-status-muted)'], // cancelled
      ['paused', 'var(--color-accent-2-400)'], // 10's nearest role
    ]
    for (const [name, value] of statuses) {
      expect(theme).toContain(`@utility text-status-${name} { color: ${value}; }`)
      expect(theme).toContain(
        `@utility border-status-${name} { border-color: ${value}; }`,
      )
    }
    // Every --ath-status-* token has one; a new one must not slip through.
    const painted = new Set(statuses.map(([name]) => `--ath-status-${name}`))
    for (const [name] of nocturneTokens()) {
      if (name.startsWith('--ath-status-')) expect(painted).toContain(name)
    }
  })

  it('carries the type scale of 10 §Type and density, base-relative', () => {
    // Exact fractions of the mock's 12 px base, never rounded decimals:
    // at the default base every one of these resolves to the pixel size
    // 10 names, and a changed base moves all six together (21 §Type
    // scale, D195).
    expect(theme).toContain(
      '@utility text-metric { font-size: calc(15rem / 12); font-weight: 500; }',
    )
    expect(theme).toContain('@utility text-row { font-size: calc(11.5rem / 12); }')
    // 11 px secondary text. The class is `text-meta`, not `text-secondary`:
    // `secondary` is a shadcn colour role, Tailwind derives
    // `.text-secondary { color: var(--secondary) }` from it, and one class
    // cannot be a size and a colour at once (D151).
    expect(theme).toContain('@utility text-meta { font-size: calc(11rem / 12); }')
    expect(theme).not.toContain('@utility text-secondary')
    expect(theme).toContain(
      '@utility text-kicker { font-size: calc(10.5rem / 12); ' +
        'text-transform: uppercase; letter-spacing: 0.12em; }',
    )
    expect(theme).toContain('@utility text-hint { font-size: calc(10rem / 12); }')
    // No absolute pixel size survives in these utilities. That is this
    // file's half of the rule only — the other half is a call site
    // writing a size of its own, which `ramp.test.ts` sweeps `src/` for
    // and `e2e/fontsize.spec.ts` measures at `xlarge`.
    for (const [, body] of theme.matchAll(/@utility text-([a-z]+) \{([^}]*)\}/g)) {
      expect(body).not.toMatch(/font-size:\s*[\d.]+px/)
    }
    // The sizes are utilities, not `--text-*` theme entries: Tailwind would
    // derive a second `text-kicker` from such an entry (see gen-theme.mjs).
    expect(theme).not.toContain('--text-kicker:')
  })

  it('gives no utility a name Tailwind already derives from a role', () => {
    // A `--color-NAME` key of `@theme inline` is a `text-NAME`, a
    // `bg-NAME` and a `border-NAME`; a `@utility` of that name would
    // share the class with it, and both rules would apply.
    const roles = [
      ...(/@theme inline \{([\s\S]*?)\n\}/.exec(theme)?.[1] ?? '').matchAll(
        /^\s*--color-([a-z0-9-]+)\s*:/gm,
      ),
    ].map((match) => match[1])
    expect(roles).toContain('secondary')
    for (const utility of generatedUtilities().keys()) {
      for (const role of roles) {
        for (const prefix of ['text-', 'bg-', 'border-']) {
          expect(utility, `${utility} collides with --color-${role}`).not.toBe(
            `${prefix}${role}`,
          )
        }
      }
    }
  })

  it('compiles every utility to what it declares and nothing else', async () => {
    // The check the unit tests above cannot make: theme.css says what a
    // class should be, this says what Tailwind makes of it once the
    // theme's own colour utilities are in the same sheet. `.text-secondary`
    // was an 11 px size *and* `color: var(--secondary)` — invisible text
    // on the page, and it beat a colour utility written beside it (D151).
    const utilities = generatedUtilities()
    expect(utilities.size).toBeGreaterThan(20)
    const compiled = await compiledProperties([...utilities.keys()])
    for (const [utility, declared] of utilities) {
      const paints = compiled.get(`.${utility}`)
      expect(paints, `.${utility} is not in the compiled stylesheet`).toBeDefined()
      for (const property of new Set(paints)) {
        expect(
          declared,
          `.${utility} also paints ${property}, which @utility ${utility} ` +
            'does not declare — another rule shares the class name',
        ).toContain(property)
      }
    }
  })

  it('mixes the chrome and zebra surfaces out of the tokens', () => {
    expect(theme).toContain(
      'background-color: color-mix(in srgb, var(--color-surface) 45%, var(--color-bg));',
    )
    expect(theme).toContain(
      'background-color: color-mix(in srgb, var(--color-surface) 60%, var(--color-bg));',
    )
    expect(theme).toMatch(/@utility bg-chrome \{/)
    expect(theme).toMatch(/@utility bg-zebra \{/)
  })

  it('keeps the two animations the mock kept and no others (D71)', () => {
    for (const name of ['ath-pulse', 'ath-caret']) {
      const declared = nocturne
        .split('\n')
        .find((line) => line.trimStart().startsWith(`@keyframes ${name} `))
      expect(declared, `nocturne.css lost @keyframes ${name}`).toBeDefined()
      const body = declared?.slice(declared.indexOf('{')).trim()
      expect(theme).toContain(`@keyframes ${name} ${body}`)
    }
    // The CRT chrome went with D71; its keyframes must not come along.
    expect(theme).not.toContain('ath-scan')
    expect(theme).not.toContain('ath-flicker')
  })

  it('stops the pulse and the caret under reduced motion (10 §Accessibility)', () => {
    expect(theme).toContain(
      '@utility animate-ath-pulse { animation: ath-pulse 1.8s ease-in-out infinite; }',
    )
    expect(theme).toContain(
      '@utility animate-ath-caret { animation: ath-caret 1s step-end infinite; }',
    )
    const guard = /@media \(prefers-reduced-motion: reduce\) \{([\s\S]*?)\n\}/.exec(
      theme,
    )?.[1]
    expect(guard).toBeDefined()
    expect(guard).toContain('.animate-ath-pulse')
    expect(guard).toContain('.animate-ath-caret')
    expect(guard).toContain('animation: none;')
  })

  it('adds no glow and no radius override (D71)', () => {
    expect(theme).not.toContain('text-shadow')
    expect(theme).not.toContain('glow-accent')
  })
})
