#!/usr/bin/env python
"""Write the generated reference of the documentation site.

The site under `docs/site/` is for someone who has just installed
Athanore, and it restates no rule (D214). Every fact with a shape — a
default, a name, a signature, a field list, a status code, a wire shape —
is generated into `docs/site/src/reference/` by this script, from the
package and from the committed OpenAPI snapshot; every hand-written page
beside it is narrative and links here for the vocabulary.

The precedent is `scripts/dump_openapi.py`, end to end: this script
renders, `docs/site/src/reference/*.md` is committed,
`tests/test_docs_site.py` asserts the committed bytes are what this
writes, and CI's `contract` job regenerates and runs `git diff
--exit-code`.

The bodies come from `scripts/_reference.py`. What is here is the
framing (the marker, the title and the lede of each page, and no citation
of `docs/v1/`, which the site does not publish) plus the two renderings
that are built here alone: the detailed HTTP reference, which walks the
snapshot operation by operation and schema by schema, and the settings
table, which is built from the descriptions on the pydantic-settings
model. `scripts/gen_skills.py` republishes these pages, links rewritten,
into `skills/*/reference/`, so a skill carries the same page rather than
a second framing of the same facts.

Determinism is the same contract as there: declaration order where it is
contract, sorted everywhere else, and no timestamps, no version numbers
and no absolute paths. `root_path`'s default is the one place that could
have produced one, and it is written out in words for exactly that
reason.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from pathlib import Path
from typing import Any

import _reference as reference
from pydantic.fields import FieldInfo

from athanore.settings import AthanoreSettings, Retention, _TomlSource

ROOT = Path(__file__).resolve().parent.parent

#: Where the generated pages go, checkout-relative.
REFERENCE = "docs/site/src/reference"

#: The first line of every file this writes. `tests/test_docs_site.py`
#: asserts it is there, and that no hand-written page carries it. It is
#: an HTML comment, so it never reaches the rendered site: "do not edit"
#: is a message for whoever opens the file, not for a reader.
MARKER = "<!-- Generated by scripts/gen_docs.py. Do not edit. -->"

#: A Sphinx cross-reference role, as it arrives in a docstring and
#: therefore in the OpenAPI snapshot. Markdown has no roles, so
#: `:class:`~athanore.events.names.EventName`` becomes `EventName`.
_ROLE = re.compile(r":[a-z]+:`([^`]+)`")

#: A markdown ATX heading, for :func:`_shift`.
_HEADING = re.compile(r"^(#{1,5}) ")

#: A dotted module path in front of a type name. `reference.type_name`
#: strips this package's own; a settings field annotated `SecretStr`
#: arrives as `pydantic.types.SecretStr`, and the module it is defined in
#: is not what an author writes.
_QUALIFIED = re.compile(r"\b(?:[A-Za-z_]\w*\.)+([A-Za-z_]\w*)")


#: One part of a parenthetical that is a citation of a design document:
#: its two-digit number, with or without a section, or a decision
#: number. The package's own docstrings carry them, so they arrive here
#: through every shared body and through the descriptions in the
#: snapshot. Exactly two digits, so `PluginError(400, ...)` keeps its
#: arguments.
_CITATION = re.compile(r"(?:\d{2}(?: §[^,;()]*)?|D\d+)")

#: A parenthetical, with the whitespace in front of it — a space, a
#: newline, or both, because a citation that opened a wrapped line would
#: otherwise leave the sentence's full stop stranded on one of its own.
#: Nested parentheses are deliberately not matched: a citation never
#: contains one.
_PARENTHETICAL = re.compile(r"( ?\n?)\(([^()]*)\)")


def _uncited(text: str) -> str:
    """``text`` with every citation of an unpublished document removed.

    The site does not publish the design documents, so `(05 §Agent
    classes)` points a reader at nothing. The sentence it hangs off
    always stands without it — the citation says where a rule is fixed,
    not what it is — so the parenthetical is dropped rather than turned
    into a broken link. A parenthetical that carries something else
    beside a citation keeps that something else.
    """

    def rebuild(match: re.Match[str]) -> str:
        parts = re.split(r"(, |; )", match.group(2))
        kept: list[str] = []
        for index in range(0, len(parts), 2):
            if _CITATION.fullmatch(parts[index].strip()):
                continue
            if kept:
                kept.append(parts[index - 1])
            kept.append(parts[index])
        if not kept:
            return ""
        return f"{match.group(1)}({''.join(kept)})"

    return _PARENTHETICAL.sub(rebuild, text)


def _page(title: str, lede: list[str], body: list[str]) -> str:
    """A title, an opening paragraph, and one generated body."""

    return reference.document(
        [title, "", *lede, "", *(_uncited(line) for line in body)], marker=MARKER
    )


def _shift(lines: list[str]) -> list[str]:
    """Every heading one level deeper.

    A body renderer opens at `##`, because it is normally the whole of a
    page. `plugins.md` carries two of them, so each is nested under a
    heading of its own and everything below it moves down with it. There
    are no fenced blocks in a generated body, so a leading `#` is always
    a heading.
    """

    return [_HEADING.sub(r"#\1 ", line) for line in lines]


def _prose(text: str) -> str:
    """A docstring as markdown: roles resolved, whitespace preserved.

    The descriptions in the snapshot are Python docstrings, so they carry
    Sphinx roles and dotted paths that mean nothing to a reader of the
    rendered page. Double backticks are left alone — they are a valid
    markdown code span already.
    """

    def name(match: re.Match[str]) -> str:
        target = match.group(1).lstrip("~").rsplit(".", 1)[-1]
        return f"`{target}`"

    return _uncited(_ROLE.sub(name, text)).strip()


def _cell(text: str) -> str:
    """One table cell: no newlines, and no pipe that would end it early."""

    return " ".join(_prose(text).split()).replace("|", "\\|")


def _annotation(field: FieldInfo) -> str:
    """A field's type, unqualified and safe inside a table cell.

    A union is spelled with `|`, which is also the column separator, so
    it is escaped here rather than in `reference.type_name` — the skills
    render the same names outside a table and want them unescaped.
    """

    text = _QUALIFIED.sub(r"\1", reference.type_name(field.annotation))
    return f"`{text}`".replace("|", "\\|")


# --------------------------------------------------------------------------
# The bodies `scripts/_reference.py` renders
# --------------------------------------------------------------------------


def _python_api() -> str:
    return _page(
        "# Python API",
        [
            "Every name `athanore` exports — what a workflow module imports.",
            "Generated from `athanore.__all__`, with the file each name is",
            "defined in, its signature, and the first line of its docstring.",
        ],
        reference.public_api(),
    )


def _node_options() -> str:
    return _page(
        "# Node options",
        [
            "The keyword options `@wf.node()` accepts, and the fields of a",
            "`Pool`. Generated from the signature of `Workflow.node()` and from",
            "the `Pool` dataclass, so the defaults here are the defaults that",
            "run. What each option is *for* is in",
            "[Writing a workflow](../guide/workflows.md).",
        ],
        reference.node_options(),
    )


def _agents() -> str:
    return _page(
        "# Agents",
        [
            "The class attributes an agent subclass may set, and the fields of",
            "the result one run returns. Generated from the `Agent` and",
            "`ACPAgent` classes and from `AgentResult`. How to use them is in",
            "[Dispatching agents](../guide/agents.md).",
        ],
        reference.agents(),
    )


def _events() -> str:
    return _page(
        "# Events",
        [
            "Every event name the server publishes, grouped as the vocabulary",
            "groups them, with the fields of the payload each one carries. A",
            "`?` marks a field that is absent rather than null when it has no",
            "value. These are the `event:` names on the SSE stream described in",
            "[Driving the API](../guide/http-api.md).",
        ],
        reference.events(),
    )


def _plugins() -> str:
    """The two plugin bodies, each nested a level down."""

    return _page(
        "# Plugins",
        [
            "What a workflow declares to reach the interface, and what a",
            "handler is handed when one of those declarations runs. Generated",
            "from the declaration dataclasses and from `PluginContext`. How to",
            "write one is in [Writing a plugin](../guide/plugins.md).",
        ],
        [
            "## Declarations",
            "",
            *_shift(reference.declarations()),
            "",
            "## `PluginContext`",
            "",
            "The one argument every plugin handler takes. Which of these a",
            "handler may reach for depends on the scope it was resolved in: a",
            "run-scoped declaration has a run, a task-scoped one has a task,",
            "and a workflow-scoped one has neither.",
            "",
            *_shift(reference.context()),
        ],
    )


def _cli() -> str:
    return _page(
        "# Command line",
        [
            "Every `athanore` command, its arguments and its options, walked",
            "off the command tree itself. What the verbs are for, and how one",
            "reaches a server, is in [The command line](../guide/cli.md).",
        ],
        reference.commands(),
    )


def _errors() -> str:
    return _page(
        "# Error codes",
        [
            "The stable `code` an error body carries. It is what a client",
            "branches on, so it outlives any wording change to the human",
            "`error` message beside it. The shape both live in is in",
            "[Driving the API](../guide/http-api.md).",
        ],
        reference.error_codes(),
    )


# --------------------------------------------------------------------------
# The HTTP reference: the snapshot, operation by operation
# --------------------------------------------------------------------------


def _schema_anchor(name: str) -> str:
    """The explicit id a schema's heading carries."""

    return f"schema-{name}"


def _type_of(schema: dict[str, Any] | None) -> str:
    """A JSON Schema rendered as a type name, with `$ref`s as links."""

    if not schema:
        return "`any`"
    if "$ref" in schema:
        name = str(schema["$ref"]).rsplit("/", 1)[-1]
        return f"[`{name}`](#{_schema_anchor(name)})"
    for key in ("anyOf", "oneOf"):
        if key in schema:
            return " \\| ".join(_type_of(each) for each in schema[key])
    if "allOf" in schema:
        return " & ".join(_type_of(each) for each in schema["allOf"])
    if "const" in schema:
        return f"`{schema['const']!r}`"
    if "enum" in schema:
        return ", ".join(f"`{value!r}`" for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"`array` of {_type_of(schema.get('items'))}"
    if kind == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"`object` of {_type_of(extra)}"
        return "`object`"
    if kind is None:
        return "`any`"
    if isinstance(kind, list):
        return " \\| ".join(f"`{each}`" for each in kind)
    fmt = schema.get("format")
    return f"`{kind}`" + (f" ({fmt})" if fmt else "")


def _parameters(operation: dict[str, Any]) -> list[str]:
    """The path, query and header parameters, as one table."""

    params = operation.get("parameters") or []
    if not params:
        return []
    lines = [
        "**Parameters**",
        "",
        "| Parameter | In | Type | Required | Description |",
        "|---|---|---|---|---|",
    ]
    for param in params:
        required = "yes" if param.get("required") else "no"
        lines.append(
            f"| `{param['name']}` | {param['in']} | "
            f"{_type_of(param.get('schema'))} | {required} "
            f"| {_cell(param.get('description', ''))} |"
        )
    lines.append("")
    return lines


def _body(operation: dict[str, Any]) -> list[str]:
    """The request body, named by its schema."""

    body = operation.get("requestBody")
    if not body:
        return []
    lines: list[str] = []
    for media, entry in sorted(body.get("content", {}).items()):
        required = " (required)" if body.get("required") else ""
        lines.append(
            f"**Request body**{required} — `{media}`, {_type_of(entry.get('schema'))}"
        )
        lines.append("")
    return lines


def _responses(operation: dict[str, Any]) -> list[str]:
    """One row per declared status."""

    responses = operation.get("responses") or {}
    lines = [
        "**Responses**",
        "",
        "| Status | Body | Description |",
        "|---|---|---|",
    ]
    for status in sorted(responses, key=lambda value: (len(value), value)):
        response = responses[status]
        schema: dict[str, Any] | None = None
        for entry in response.get("content", {}).values():
            schema = entry.get("schema")
            break
        rendered = _type_of(schema) if schema is not None else "empty"
        lines.append(
            f"| `{status}` | {rendered} | {_cell(response.get('description', ''))} |"
        )
    lines.append("")
    return lines


def _operations(spec: dict[str, Any]) -> list[str]:
    """One `##` per tag, in the document's tag order, then its operations."""

    by_tag: dict[str, list[tuple[str, str, dict[str, Any]]]] = {}
    for path, item in spec["paths"].items():
        for method, operation in item.items():
            for tag in operation.get("tags") or ["untagged"]:
                by_tag.setdefault(tag, []).append((path, method.upper(), operation))

    declared = [tag["name"] for tag in spec.get("tags", [])]
    order = declared + sorted(set(by_tag) - set(declared))
    described = {
        tag["name"]: tag.get("description", "") for tag in spec.get("tags", [])
    }

    lines: list[str] = []
    for tag in order:
        entries = by_tag.get(tag)
        if not entries:
            continue
        lines += [f"## {tag}", ""]
        if described.get(tag):
            lines += [_prose(described[tag]), ""]
        for path, method, operation in sorted(entries):
            operation_id = operation.get("operationId", "")
            lines += [
                f"### `{method} {path}` {{#op-{operation_id}}}",
                "",
            ]
            if operation.get("summary"):
                lines += [_prose(operation["summary"]), ""]
            lines += [
                f"Credential: {reference.credential(operation)}. "
                f"Operation id: `{operation_id}`.",
                "",
            ]
            if operation.get("description"):
                lines += [_prose(operation["description"]), ""]
            lines += _parameters(operation)
            lines += _body(operation)
            lines += _responses(operation)
    return lines


def _schemas(spec: dict[str, Any]) -> list[str]:
    """Every entry of `components.schemas`, sorted, as a field table."""

    lines = ["## Schemas", ""]
    schemas: dict[str, Any] = spec.get("components", {}).get("schemas", {})
    for name in sorted(schemas):
        schema = schemas[name]
        lines += [f"### `{name}` {{#{_schema_anchor(name)}}}", ""]
        if schema.get("description"):
            lines += [_prose(schema["description"]), ""]
        if "enum" in schema:
            lines += [f"- `{value!r}`" for value in schema["enum"]]
            lines.append("")
            continue
        properties: dict[str, Any] = schema.get("properties") or {}
        if not properties:
            lines += [f"Type: {_type_of(schema)}", ""]
            continue
        required = set(schema.get("required") or ())
        lines += ["| Field | Type | Required | Description |", "|---|---|---|---|"]
        for field, entry in properties.items():
            mark = "yes" if field in required else "no"
            lines.append(
                f"| `{field}` | {_type_of(entry)} | {mark} "
                f"| {_cell(entry.get('description', ''))} |"
            )
        lines.append("")
    return lines


def _http_api() -> str:
    spec = reference.snapshot()
    return _page(
        "# HTTP API",
        [
            "Every operation the server exposes, generated from the OpenAPI",
            "document it produces. The credential column is what the operation",
            "requires: `operator` is the operator token (or nothing at all on a",
            "loopback bind), `task` is the per-task token an agent is given.",
            "How to authenticate, read the event stream and generate a client",
            "is in [Driving the API](../guide/http-api.md).",
        ],
        [
            *reference.route_table(),
            "",
            *_operations(spec),
            *_schemas(spec),
            "The document all of this is generated from is published beside",
            "this page: [openapi.json](../openapi.json).",
        ],
    )


# --------------------------------------------------------------------------
# The settings table
# --------------------------------------------------------------------------

#: The two settings `athanore.toml` refuses, read off the source that
#: refuses them so the column cannot drift from the behaviour.
_REFUSED = _TomlSource._REFUSED_KEYS

#: The two tables `athanore serve` reads and the settings model ignores.
_IGNORED = _TomlSource._IGNORED_TABLES


def _default_of(field: FieldInfo) -> str:
    """A field's default, as a reader should see it written.

    A `default_factory` is called, because the value is the default a
    reader gets. The one exception is a `Path`: `root_path`'s factory is
    `Path.cwd`, and rendering what it returns would put this machine's
    absolute path into a committed file. It is written out in words
    instead, and `tests/test_docs_site.py` asserts the page has no
    absolute path in it.
    """

    if field.default_factory is not None:
        value = field.default_factory()  # type: ignore[call-arg]
    else:
        value = field.default
    if value is None:
        return "*unset*"
    if isinstance(value, Path):
        return "the working directory"
    return f"`{value!r}`"


def _settings_rows(model: type[Any], *, prefix: str) -> list[str]:
    """One row per field, in declaration order."""

    lines = [
        "| Setting | Environment variable | `athanore.toml` | Type | Default "
        "| Description |",
        "|---|---|---|---|---|---|",
    ]
    for name, field in model.model_fields.items():
        env = f"`{prefix}{name.upper()}`" if prefix else "—"
        key = "*refused*" if name in _REFUSED else f"`{name}`"
        lines.append(
            f"| `{name}` | {env} | {key} | {_annotation(field)} "
            f"| {_default_of(field)} | {_cell(field.description or '')} |"
        )
    lines.append("")
    return lines


def _settings() -> str:
    retention = Retention()
    ignored = ", ".join(f"`[{table}]`" for table in sorted(_IGNORED))
    refused = ", ".join(f"`{name}`" for name in sorted(_REFUSED))
    return _page(
        "# Settings",
        [
            "Every setting, its environment variable, its `athanore.toml` key,",
            "its type and its default. Generated from the settings model, so a",
            "default here is the default that runs. Precedence is command-line",
            "flags first, then the environment, then `athanore.toml` in the root",
            "path, then these defaults.",
        ],
        [
            *_settings_rows(AthanoreSettings, prefix="ATHANORE_"),
            "## `[retention]`",
            "",
            "A nested table rather than a top-level key, so these have no",
            "environment variable of their own: set them in the `[retention]`",
            "table of `athanore.toml`, or together as JSON in",
            "`ATHANORE_RETENTION`.",
            "",
            *_settings_rows(Retention, prefix=""),
            "## `athanore.toml`",
            "",
            "One file beside the database. Top-level keys are the settings in",
            "the first table above, spelled as their `athanore.toml` column;",
            f"{refused} are refused there and are set from the environment or",
            "the command line instead. An unknown top-level key is an error at",
            f"startup rather than a silent default. {ignored} are read by",
            "`athanore serve` rather than by the settings model.",
            "",
            "```toml",
            'host = "127.0.0.1"',
            "port = 4002",
            "workers = 2",
            "",
            "[retention]",
            f"events_days = {retention.events_days}",
            f"stream_days = {retention.stream_days}",
            "",
            "[pools]",
            "build = 2",
            "",
            "[workflows]",
            'feature_build = { pool = "build" }',
            "```",
        ],
    )


# --------------------------------------------------------------------------
# The targets
# --------------------------------------------------------------------------

#: Every file this script owns, checkout-relative, and what renders it.
#: `tests/test_docs_site.py` reads this table: a file under
#: `docs/site/src/reference/` that is not in it is an orphan, and one in
#: it that is not on disk is missing.
TARGETS: dict[str, Callable[[], str]] = {
    f"{REFERENCE}/python-api.md": _python_api,
    f"{REFERENCE}/node-options.md": _node_options,
    f"{REFERENCE}/agents.md": _agents,
    f"{REFERENCE}/events.md": _events,
    f"{REFERENCE}/plugins.md": _plugins,
    f"{REFERENCE}/cli.md": _cli,
    f"{REFERENCE}/http-api.md": _http_api,
    f"{REFERENCE}/errors.md": _errors,
    f"{REFERENCE}/settings.md": _settings,
}


def render(target: str) -> str:
    """The exact text of one generated page, as it stands."""

    try:
        renderer = TARGETS[target]
    except KeyError:
        raise KeyError(f"{target} is not a file scripts/gen_docs.py writes") from None
    return renderer()


def main() -> None:
    for target in TARGETS:
        path = ROOT / target
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(target), encoding="utf-8")
        print(f"wrote {target}")


if __name__ == "__main__":
    main()
