#!/usr/bin/env python
"""Republish the documentation site's pages into every skill under `skills/`.

A skill is installed into somebody else's coding agent, working on their
own project, with no checkout of this repository on disk. So a skill
stands alone: everything an agent needs in order to write a workflow, a
plugin, an API client or a command line against Athanore is in the
directory that was copied, and every link in it resolves inside that
directory.

Rather than hand-write a second narrative per skill — which would drift
from the site within a release — each skill's `reference/` is the site's
own pages, republished. The guide pages under `docs/site/src/guide/` are
the narrative half; the pages `scripts/gen_docs.py` generates from the
code and the committed OpenAPI snapshot are the fact half. This script
copies the pages each skill bundles (:data:`BUNDLES`), rewrites their
links so a copied skill resolves every one inside itself (:func:`rewrite`),
and stamps each copy with :data:`MARKER`. The `SKILL.md` beside them is
hand-written and is the minimum to act.

The precedent is `scripts/dump_openapi.py`, end to end: this script
renders, `skills/*/reference/*` is committed, `tests/test_skills.py`
asserts the committed bytes are what this renders, and CI's `contract`
job regenerates and runs `git diff --exit-code`.

Determinism is the whole point, as it is there. No timestamps, no version
numbers, no absolute paths: every output is a pure function of committed
files and of what `gen_docs.py` renders in process. Every markdown file
begins with :data:`MARKER` and ends with a trailing newline; the one
non-markdown target, the OpenAPI document, is the snapshot byte for byte.

`scripts/` is dev machinery rather than a package. Nothing in `athanore/`
imports this, and this starts no server, opens no database and reaches no
network.
"""

from __future__ import annotations

import posixpath
import re
from collections.abc import Callable
from pathlib import Path

import _reference as reference
import gen_docs

ROOT = Path(__file__).resolve().parent.parent

#: Where the site's pages live, checkout-relative. Every page name in
#: :data:`BUNDLES` is relative to this.
SITE = "docs/site/src"

#: The first line of every markdown file this writes. `tests/test_skills.py`
#: asserts it is there, and that no hand-written skill file carries it.
MARKER = "<!-- Generated by scripts/gen_skills.py. Do not edit. -->"

#: The one page that is not markdown: the committed OpenAPI document, which
#: the site publishes at its root and the HTTP pages link as
#: `../openapi.json`. Bundling it is what makes those links resolve.
OPENAPI = "openapi.json"

#: The pages each skill republishes, as site paths, in the order the
#: skill's `SKILL.md` lists them. A page appears in more than one bundle
#: because no skill may depend on another being installed: a generated
#: copy is free, and a cross-skill link is a dangling one the moment a
#: user installs one skill. The web skill bundles nothing: its facts are
#: TypeScript, already generated and gated under `web/`.
BUNDLES: dict[str, tuple[str, ...]] = {
    "athanore-workflows": (
        "guide/workflows.md",
        "guide/agents.md",
        "guide/human-in-the-loop.md",
        "guide/runs.md",
        "reference/python-api.md",
        "reference/node-options.md",
        "reference/agents.md",
        "reference/events.md",
    ),
    "athanore-plugins": (
        "guide/plugins.md",
        "reference/plugins.md",
        "reference/events.md",
        "reference/settings.md",
    ),
    "athanore-api": (
        "guide/http-api.md",
        "reference/http-api.md",
        "reference/errors.md",
        "reference/events.md",
        OPENAPI,
    ),
    "athanore-cli": (
        "guide/cli.md",
        "guide/deployment.md",
        "reference/cli.md",
        "reference/settings.md",
    ),
}

#: One markdown link. The text may wrap a line — a link at the end of a
#: wrapped sentence does — so it admits newlines; the target may not
#: contain whitespace or a parenthesis, which keeps a list comprehension
#: in a Python fence from looking like one.
LINK = re.compile(r"\[([^\[\]]+)\]\(([^()\s]+)\)")


def filename(page: str) -> str:
    """Where a site page lands inside a skill's `reference/`.

    `guide/x.md` becomes `guide-x.md` and `reference/x.md` becomes
    `x.md`, so a bundle is one flat directory and a guide is told apart
    from the reference it links by its name.
    """

    if page.startswith("guide/"):
        return "guide-" + page[len("guide/") :]
    if page.startswith("reference/"):
        return page[len("reference/") :]
    return page


def home(page: str) -> str | None:
    """The first skill, in :data:`BUNDLES` order, that carries ``page``."""

    for skill, bundle in BUNDLES.items():
        if page in bundle:
            return skill
    return None


def rewrite(text: str, *, page: str, skill: str) -> str:
    """``text`` — the site page ``page`` — with its links resolving in ``skill``.

    One rule, applied to every `[text](target)`:

    - an external link (`://`) or a fragment-only one (`#…`) is untouched;
    - a link to a page in this skill's bundle becomes a link to that
      file, fragment kept, so it resolves inside the copied directory;
    - a link to a page another skill bundles becomes its text followed by
      the skill that carries it, so the reader learns what to install
      rather than finding a broken link;
    - a link to anything else becomes its text alone.

    Targets are resolved against the directory of ``page``, so
    `../reference/events.md` from a guide and `../guide/http-api.md` from
    a reference page both name the site page they name on the site.
    """

    bundle = BUNDLES[skill]
    directory = posixpath.dirname(page)

    def resolve(match: re.Match[str]) -> str:
        label, target = match.group(1), match.group(2)
        if "://" in target or target.startswith("#"):
            return match.group(0)
        path, _, fragment = target.partition("#")
        resolved = posixpath.normpath(posixpath.join(directory, path))
        if resolved in bundle:
            suffix = f"#{fragment}" if fragment else ""
            return f"[{label}]({filename(resolved)}{suffix})"
        carrier = home(resolved)
        if carrier is not None:
            return f"{label} (see the {carrier} skill)"
        return label

    return LINK.sub(resolve, text)


def page_text(page: str) -> str:
    """The site page ``page``, as this script's own output before rewriting.

    A reference page is rendered in process by `gen_docs.py` — never read
    from `docs/site/src/reference/` on disk, so the order the two
    generators run in cannot matter — with its first line, the site's
    marker, replaced by this script's and nothing else touched. A guide
    is read from disk and wrapped in the marker and a blank line. The
    OpenAPI document is the committed snapshot, byte for byte: JSON has
    no comment to carry a marker in.
    """

    if page == OPENAPI:
        return reference.SNAPSHOT.read_text(encoding="utf-8")
    if page.startswith("reference/"):
        rendered = gen_docs.render(f"{SITE}/{page}")
        first, newline, rest = rendered.partition("\n")
        assert first == gen_docs.MARKER, page
        return MARKER + newline + rest
    lines = (ROOT / SITE / page).read_text(encoding="utf-8").splitlines()
    return reference.document(lines, marker=MARKER)


def _renderer(page: str, skill: str) -> Callable[[], str]:
    if page == OPENAPI:
        return lambda: page_text(page)
    return lambda: rewrite(page_text(page), page=page, skill=skill)


#: Every file this script owns, checkout-relative, and what renders it.
#: `tests/test_skills.py` reads this table: a file under a `reference/`
#: directory that is not in it is an orphan, and one in it that is not on
#: disk is missing.
TARGETS: dict[str, Callable[[], str]] = {
    f"skills/{skill}/reference/{filename(page)}": _renderer(page, skill)
    for skill, bundle in BUNDLES.items()
    for page in bundle
}


def render(target: str) -> str:
    """The exact text of one generated file, as it stands."""

    try:
        renderer = TARGETS[target]
    except KeyError:
        raise KeyError(f"{target} is not a file scripts/gen_skills.py writes") from None
    return renderer()


def main() -> None:
    for target in TARGETS:
        path = ROOT / target
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(target), encoding="utf-8")
        print(f"wrote {target}")


if __name__ == "__main__":
    main()
