#!/usr/bin/env python
"""Write the generated reference of every skill under `skills/`.

A skill is a pointer, never a copy (D213): a `SKILL.md` is hand-written
and states no fact that is written down somewhere else, and every fact it
would otherwise have restated is generated here — the public API, the
node options, the agent attributes, the event vocabulary, the plugin
declarations and the context a handler is handed, the route table and the
command tree.

The precedent is `scripts/dump_openapi.py`, end to end: this script
renders, `skills/*/reference/*.md` is committed, `tests/test_skills.py`
asserts the committed bytes are what this renders, and CI's `contract`
job regenerates and runs `git diff --exit-code`.

What is left here is the framing — the marker, the title and the opening
paragraph of each file. The bodies are `scripts/_reference.py`, which
`scripts/gen_docs.py` renders too: the facts are the same facts and only
the framing differs, so there is one renderer with two front ends
(D214). This one cites the specification, because its reader has the
checkout open; the site's does not.

Determinism is the whole point, as it is there. No timestamps, no version
numbers, no absolute paths, no ordering that can vary between runs: enum
members and dataclass fields keep declaration order, which is contract,
and everything else is sorted. Every file begins with :data:`MARKER` and
ends with a trailing newline.

`scripts/` is dev machinery rather than a package. Nothing in `athanore/`
imports this, and this starts no server, opens no database and reaches no
network — it imports the package, reads its own tree, and reads the
committed OpenAPI snapshot.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import _reference as reference

ROOT = Path(__file__).resolve().parent.parent

#: The first line of every file this writes. `tests/test_skills.py`
#: asserts it is there, and that no hand-written skill file carries it.
MARKER = "<!-- Generated by scripts/gen_skills.py. Do not edit. -->"


def _page(title: str, lede: list[str], body: list[str]) -> str:
    """A title, an opening paragraph, and one generated body."""

    return reference.document([title, "", *lede, "", *body], marker=MARKER)


# --------------------------------------------------------------------------
# skills/athanore-workflows/reference
# --------------------------------------------------------------------------


def _public_api() -> str:
    return _page(
        "# The public API",
        [
            "Every name in `athanore.__all__`, read off `athanore/__init__.py`.",
            "The surface is fixed by",
            "`docs/v1/02-architecture.md` §Public API (`athanore/__init__.py`).",
            "The deprecated MVP aliases are not in `__all__`, and are not listed",
            "here.",
        ],
        reference.public_api(),
    )


def _node_options() -> str:
    return _page(
        "# Node options and pools",
        [
            "The keyword parameters of `Workflow.node()` in `athanore/workflow.py`,",
            "which is the metadata seam of",
            "`docs/v1/04-engine.md` §Node options (metadata seam), and the fields",
            "of `Pool` in `athanore/engine/pools.py` (`docs/v1/04-engine.md` §Pools).",
        ],
        reference.node_options(),
    )


def _agents() -> str:
    return _page(
        "# Agent classes",
        [
            "The class attributes a subclass may set, read off",
            "`athanore/agents/base.py` and `athanore/agents/acp.py`, and the",
            "fields of `AgentResult`. What each one means is",
            "`docs/v1/05-agents.md` §Agent classes; the permission and",
            "elicitation attributes are `docs/v1/05-agents.md` §Policies.",
        ],
        reference.agents(),
    )


def _events() -> str:
    return _page(
        "# The event vocabulary",
        [
            "Every member of `EventName` in `athanore/events/names.py`, with the",
            "fields of the payload it carries from `athanore/events/payloads.py`.",
            "The names are fixed by `docs/v1/03-domain-model.md` §Event",
            "vocabulary and the payloads by `docs/v1/18-event-payloads.md`",
            "§Payloads. A `?` marks a field that is absent rather than null when",
            "it has no value (`docs/v1/18-event-payloads.md` §Rules). The",
            "envelope these travel in — what it carries besides `data`, and",
            "which of those may be absent — is `docs/v1/18-event-payloads.md`",
            "§Envelope.",
        ],
        reference.events(),
    )


# --------------------------------------------------------------------------
# skills/athanore-plugins/reference
# --------------------------------------------------------------------------


def _declarations() -> str:
    return _page(
        "# Plugin declarations",
        [
            "The dataclasses a `@wf.route`, `@wf.action`, `wf.panel(...)` and",
            "`@wf.on(...)` produce, read off `athanore/plugins/decl.py`. What each",
            "one means is `docs/v1/09-plugins.md` §Declarations; the decorators",
            "that build them are `athanore/workflow.py`.",
        ],
        reference.declarations(note=reference.cite),
    )


def _context() -> str:
    return _page(
        "# `PluginContext`",
        [
            "The one argument every plugin handler takes, read off",
            "`athanore/plugins/context.py`. Which of these a handler may reach",
            "for depends on the scope it was resolved in:",
            "`docs/v1/09-plugins.md` §Context and scopes.",
        ],
        reference.context(note=reference.cite),
    )


# --------------------------------------------------------------------------
# skills/athanore-api/reference
# --------------------------------------------------------------------------


def _routes() -> str:
    """One row per operation of the committed OpenAPI snapshot.

    Read from `tests/snapshots/openapi.json` rather than from
    `create_app()`, so that a stale snapshot fails one check — the
    OpenAPI one — instead of two, and so this script never builds an
    application.
    """

    return _page(
        "# The route table",
        [
            "Every operation of `tests/snapshots/openapi.json`, the wire contract",
            "of `docs/v1/08-api.md` §Endpoints, generated from the code. The",
            "credential column is what the operation declares:",
            "`docs/v1/08-api.md` §Authentication (12 has the model).",
        ],
        reference.route_table(),
    )


def _error_codes() -> str:
    return _page(
        "# Error codes",
        [
            "The stable `code` of an error body, read off",
            "`athanore/api/errors.py`. The shape it appears in and what each one",
            "means is `docs/v1/08-api.md` §Conventions.",
        ],
        reference.error_codes(),
    )


# --------------------------------------------------------------------------
# skills/athanore-cli/reference
# --------------------------------------------------------------------------


def _commands() -> str:
    return _page(
        "# The command tree",
        [
            "`athanore`, as `athanore/cli/__init__.py` and the verb modules",
            "beside it build it. What each verb is for is",
            "`docs/v1/11-cli.md` §Verbs; how a verb reaches a server is",
            "`docs/v1/11-cli.md` §Client connection; what it exits with is",
            "`docs/v1/11-cli.md` §Exit codes.",
        ],
        reference.commands(),
    )


# --------------------------------------------------------------------------
# The targets
# --------------------------------------------------------------------------

#: Every file this script owns, checkout-relative, and what renders it.
#: `tests/test_skills.py` reads this table: a file under a `reference/`
#: directory that is not in it is an orphan, and one in it that is not on
#: disk is missing.
TARGETS: dict[str, Callable[[], str]] = {
    "skills/athanore-workflows/reference/public-api.md": _public_api,
    "skills/athanore-workflows/reference/node-options.md": _node_options,
    "skills/athanore-workflows/reference/agents.md": _agents,
    "skills/athanore-workflows/reference/events.md": _events,
    "skills/athanore-plugins/reference/declarations.md": _declarations,
    "skills/athanore-plugins/reference/context.md": _context,
    "skills/athanore-api/reference/routes.md": _routes,
    "skills/athanore-api/reference/error-codes.md": _error_codes,
    "skills/athanore-cli/reference/commands.md": _commands,
}


def render(target: str) -> str:
    """The exact text of one generated file, as it stands."""

    try:
        renderer = TARGETS[target]
    except KeyError:
        raise KeyError(f"{target} is not a file scripts/gen_skills.py writes") from None
    return renderer()


def main() -> None:
    for target in TARGETS:
        path = ROOT / target
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(target), encoding="utf-8")
        print(f"wrote {target}")


if __name__ == "__main__":
    main()
