#!/usr/bin/env python
"""Write the generated reference of every skill under `skills/`.

A skill is a pointer, never a copy (D213): a `SKILL.md` is hand-written
and states no fact that is written down somewhere else, and every fact it
would otherwise have restated is generated here — the public API, the
node options, the agent attributes, the event vocabulary, the plugin
declarations and the context a handler is handed, the route table and the
command tree.

The precedent is `scripts/dump_openapi.py`, end to end: this script
renders, `skills/*/reference/*.md` is committed, `tests/test_skills.py`
asserts the committed bytes are what this renders, and CI's `contract`
job regenerates and runs `git diff --exit-code`.

Determinism is the whole point, as it is there. No timestamps, no version
numbers, no absolute paths, no ordering that can vary between runs: enum
members and dataclass fields keep declaration order, which is contract,
and everything else is sorted. Every file begins with :data:`MARKER` and
ends with a trailing newline.

`scripts/` is dev machinery rather than a package. Nothing in `athanore/`
imports this, and this starts no server, opens no database and reaches no
network — it imports the package, reads its own tree, and reads the
committed OpenAPI snapshot.
"""

from __future__ import annotations

import dataclasses
import inspect
import json
import re
from collections.abc import Callable
from enum import Enum
from pathlib import Path
from types import NoneType
from typing import Any

from pydantic import BaseModel
from typer.main import get_command

import athanore
from athanore.agents.acp import ACPAgent
from athanore.agents.base import Agent, AgentResult
from athanore.api.errors import ErrorCode
from athanore.cli import app as cli_app
from athanore.engine.ops import Ops
from athanore.engine.pools import Pool
from athanore.events.names import EPHEMERAL, EventName
from athanore.events.payloads import PAYLOADS
from athanore.plugins import decl
from athanore.plugins.context import NO_RUN, NO_TASK, PluginContext, PluginServices
from athanore.workflow import Workflow

ROOT = Path(__file__).resolve().parent.parent

#: The first line of every file this writes. `tests/test_skills.py`
#: asserts it is there, and that no hand-written skill file carries it.
MARKER = "<!-- Generated by scripts/gen_skills.py. Do not edit. -->"


# --------------------------------------------------------------------------
# Rendering helpers
# --------------------------------------------------------------------------


def _document(lines: list[str]) -> str:
    """The marker, the body, one trailing newline, no trailing blanks."""

    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join([MARKER, "", *lines]) + "\n"


def _first_line(text: str | None) -> str:
    """The first non-empty line of a docstring, whitespace collapsed."""

    for line in (text or "").strip().splitlines():
        if line.strip():
            return " ".join(line.split())
    return ""


def _summary(value: Any) -> str:
    """The one-line summary of a class or a function's own docstring.

    ``__doc__`` off the object rather than :func:`inspect.getdoc`, which
    walks the MRO: an exception class with no docstring of its own would
    otherwise be described by :class:`Exception`'s.
    """

    if not (inspect.isclass(value) or inspect.isroutine(value)):
        return ""
    return _first_line(getattr(value, "__doc__", None))


def _signature(value: Any) -> str | None:
    """``(a: int, *, b: str = 'x')`` for what has one, else ``None``.

    Rendered parameter by parameter rather than by ``str()`` of the
    :class:`inspect.Signature`, because every module here carries ``from
    __future__ import annotations``: the annotations arrive as source
    strings and the default repr quotes each one, which is not what an
    author would type.
    """

    if not (inspect.isclass(value) or inspect.isroutine(value)):
        return None
    try:
        signature = inspect.signature(value)
    except (TypeError, ValueError):  # pragma: no cover - builtins only
        return None
    kinds = inspect.Parameter
    parts: list[str] = []
    previous: Any = None
    seen_star = False
    for name, parameter in signature.parameters.items():
        if name == "self":
            continue
        if previous is kinds.POSITIONAL_ONLY and parameter.kind is not previous:
            parts.append("/")
        if parameter.kind is kinds.KEYWORD_ONLY and not seen_star:
            parts.append("*")
        if parameter.kind in (kinds.VAR_POSITIONAL, kinds.KEYWORD_ONLY):
            seen_star = True
        text = name
        if parameter.kind is kinds.VAR_POSITIONAL:
            text = f"*{name}"
        elif parameter.kind is kinds.VAR_KEYWORD:
            text = f"**{name}"
        annotated = parameter.annotation is not kinds.empty
        if annotated:
            text += f": {_type(parameter.annotation)}"
        if parameter.default is not kinds.empty:
            joiner = " = " if annotated else "="
            text += f"{joiner}{_default(parameter.default)}"
        parts.append(text)
        previous = parameter.kind
    if previous is kinds.POSITIONAL_ONLY:
        parts.append("/")
    rendered = f"({', '.join(parts)})"
    returns = signature.return_annotation
    if not inspect.isclass(value) and returns is not inspect.Signature.empty:
        rendered += f" -> {_type(returns)}"
    return rendered


def _type(annotation: Any) -> str:
    """A stable spelling of an annotation, resolved or still a string.

    The payload models resolve theirs (pydantic does it at class
    creation), so what arrives here is sometimes a type object, and
    ``str()`` of one carries ``typing.`` prefixes, ``<class '...'>``
    wrappers and module paths that no author writes.
    """

    if annotation is None or annotation is NoneType:
        return "None"
    if isinstance(annotation, str):
        text = annotation
    elif isinstance(annotation, type):
        return annotation.__name__
    else:
        text = str(annotation)
    text = text.replace("typing.", "")
    text = re.sub(r"<class '([^']+)'>", lambda m: m.group(1).rsplit(".", 1)[-1], text)
    text = re.sub(r"\bathanore(?:\.\w+)*\.(\w+)", r"\1", text)
    if text.startswith("Optional[") and text.endswith("]"):
        text = f"{text[len('Optional[') : -1]} | None"
    return text


def _default(value: Any) -> str:
    """How a default is written: by name for a class or an enum member."""

    if inspect.isclass(value):
        return value.__name__
    if isinstance(value, Enum):
        return f"{type(value).__name__}.{value.name}"
    return repr(value)


def _relative(obj: Any) -> str | None:
    """The checkout-relative file ``obj`` is defined in, if there is one."""

    try:
        source = inspect.getsourcefile(obj)
    except TypeError:
        return None
    if source is None:  # pragma: no cover - C extensions only
        return None
    try:
        return Path(source).resolve().relative_to(ROOT).as_posix()
    except ValueError:  # pragma: no cover - an installed copy, not a checkout
        return None


def _annotated_attributes(cls: type) -> list[tuple[str, str, str]]:
    """``(name, annotation, default)`` for a class's own annotated attributes.

    ``__annotations__`` off the class itself, so a subclass lists what it
    adds rather than repeating its base. The annotations are the source
    strings — every module here carries ``from __future__ import
    annotations`` — which is exactly what an author would type.
    """

    out: list[tuple[str, str, str]] = []
    for name, annotation in vars(cls).get("__annotations__", {}).items():
        if name.startswith("_"):
            continue
        out.append((name, _type(annotation), _default(getattr(cls, name))))
    return out


def _dataclass_fields(cls: type) -> list[tuple[str, str, str | None]]:
    """``(name, annotation, default)`` per public field, in declaration order."""

    out: list[tuple[str, str, str | None]] = []
    for field in dataclasses.fields(cls):  # type: ignore[arg-type]
        if field.name.startswith("_"):
            continue
        annotation = _type(field.type)
        if field.default is not dataclasses.MISSING:
            default: str | None = _default(field.default)
        elif field.default_factory is not dataclasses.MISSING:
            # `dict`, `list`, `tuple` — what a `default_factory` is in
            # practice, and the name is what an author would have written.
            default = f"{getattr(field.default_factory, '__name__', 'factory')}()"
        else:
            default = None
        out.append((field.name, annotation, default))
    return out


def _declaration(name: str, annotation: str, default: str | None) -> str:
    """One ``- `name: type = default`` bullet."""

    text = f"{name}: {annotation}"
    if default is not None:
        text += f" = {default}"
    return f"- `{text}`"


def _members(cls: type[Enum]) -> list[str]:
    """One bullet per enum member, in declaration order.

    The value is written out only where it differs from the member name —
    ``global_`` is spelled ``global`` on the wire, and it is the only one.
    """

    return [
        f"- `{member.name}`"
        + (f" = `{member.value}`" if member.name != member.value else "")
        for member in cls
    ]


def _methods(cls: type, *, title: str) -> list[str]:
    """A heading and one bullet per public method of ``cls``."""

    where = _relative(cls)
    lines = [f"{title}" + (f" — `{where}`" if where else ""), ""]
    for name, member in sorted(vars(cls).items()):
        if name.startswith("_") or not inspect.isroutine(member):
            continue
        signature = _signature(member) or "(...)"
        signature = signature.replace("(self, ", "(").replace("(self)", "()")
        prefix = "await " if inspect.iscoroutinefunction(member) else ""
        lines.append(f"- `{prefix}{name}{signature}`")
        summary = _summary(member)
        if summary:
            lines.append(f"  - {summary}")
    lines.append("")
    return lines


# --------------------------------------------------------------------------
# skills/athanore-workflows/reference
# --------------------------------------------------------------------------


def _public_api() -> str:
    """Every name `athanore` exports, resolved through its `__getattr__`."""

    lines = [
        "# The public API",
        "",
        "Every name in `athanore.__all__`, read off `athanore/__init__.py`.",
        "The surface is fixed by",
        "`docs/v1/02-architecture.md` §Public API (`athanore/__init__.py`).",
        "The deprecated MVP aliases are not in `__all__`, and are not listed",
        "here.",
        "",
    ]
    for name in sorted(athanore.__all__):
        value = getattr(athanore, name)
        if inspect.isclass(value):
            kind = "class"
        elif inspect.isroutine(value):
            kind = "function"
        else:
            kind = type(value).__name__
        where = _relative(value) or "athanore/__init__.py"
        lines.append(f"- **`{name}`** — {kind}, `{where}`")
        signature = _signature(value)
        if signature is not None:
            lines.append(f"  - `{name}{signature}`")
        summary = _summary(value)
        if summary:
            lines.append(f"  - {summary}")
    return _document(lines)


def _node_options() -> str:
    """The metadata seam: `wf.node()`'s keywords, and `Pool`'s fields."""

    lines = [
        "# Node options and pools",
        "",
        "The keyword parameters of `Workflow.node()` in `athanore/workflow.py`,",
        "which is the metadata seam of",
        "`docs/v1/04-engine.md` §Node options (metadata seam), and the fields",
        "of `Pool` in `athanore/engine/pools.py` (`docs/v1/04-engine.md` §Pools).",
        "",
        "## `@wf.node(...)`",
        "",
    ]
    for name, parameter in inspect.signature(Workflow.node).parameters.items():
        if name == "self" or parameter.kind is inspect.Parameter.VAR_KEYWORD:
            continue
        if parameter.kind is inspect.Parameter.KEYWORD_ONLY:
            lines.append(
                _declaration(
                    name, _type(parameter.annotation), _default(parameter.default)
                )
            )
    lines += ["", "## `Pool`", ""]
    for name, annotation, default in _dataclass_fields(Pool):
        lines.append(_declaration(name, annotation, default))
    return _document(lines)


def _agents() -> str:
    """What an agent subclass may set, and what one run returns."""

    lines = [
        "# Agent classes",
        "",
        "The class attributes a subclass may set, read off",
        "`athanore/agents/base.py` and `athanore/agents/acp.py`, and the",
        "fields of `AgentResult`. What each one means is",
        "`docs/v1/05-agents.md` §Agent classes; the permission and",
        "elicitation attributes are `docs/v1/05-agents.md` §Policies.",
        "",
        "## `Agent`",
        "",
    ]
    for name, annotation, default in _annotated_attributes(Agent):
        lines.append(_declaration(name, annotation, default))
    lines += [
        "",
        "## `ACPAgent`",
        "",
        "Adds to `Agent`, and inherits the three above.",
        "",
    ]
    for name, annotation, default in _annotated_attributes(ACPAgent):
        lines.append(_declaration(name, annotation, default))
    lines += ["", "## `AgentResult`", ""]
    for name, annotation, default in _dataclass_fields(AgentResult):
        lines.append(_declaration(name, annotation, default))
    lines.append(f"- `ok` — property: {_first_line(AgentResult.ok.__doc__)}")
    return _document(lines)


def _event_groups() -> list[tuple[str, list[EventName]]]:
    """`EventName`'s members, grouped by the comment blocks of its source."""

    groups: list[tuple[str, list[EventName]]] = []
    for line in inspect.getsource(EventName).splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            groups.append((stripped[2:].strip(), []))
        elif "=" in stripped:
            member = EventName.__members__.get(stripped.split("=", 1)[0].strip())
            if member is not None:
                if not groups:
                    groups.append(("Events", []))
                groups[-1][1].append(member)
    grouped = [(title, members) for title, members in groups if members]
    seen = {member for _, members in grouped for member in members}
    missing = [member.value for member in EventName if member not in seen]
    if missing:
        raise RuntimeError(
            f"athanore/events/names.py has members no comment block covers: "
            f"{missing}. Group them, or this reference would drop them silently."
        )
    return grouped


def _payload_fields(model: type[BaseModel]) -> str:
    """One payload's wire fields: ``key?: type``, in declaration order."""

    parts: list[str] = []
    for name, field in model.model_fields.items():
        key = field.serialization_alias or name
        mark = "" if field.is_required() else "?"
        parts.append(f"`{key}{mark}: {_type(field.annotation)}`")
    return ", ".join(parts) if parts else "no fields"


def _events() -> str:
    """The vocabulary, and the payload each name carries."""

    lines = [
        "# The event vocabulary",
        "",
        "Every member of `EventName` in `athanore/events/names.py`, with the",
        "fields of the payload it carries from `athanore/events/payloads.py`.",
        "The names are fixed by `docs/v1/03-domain-model.md` §Event",
        "vocabulary and the payloads by `docs/v1/18-event-payloads.md`",
        "§Payloads. A `?` marks a field that is absent rather than null when",
        "it has no value (`docs/v1/18-event-payloads.md` §Rules). The",
        "envelope these travel in — what it carries besides `data`, and",
        "which of those may be absent — is `docs/v1/18-event-payloads.md`",
        "§Envelope.",
        "",
    ]
    for title, members in _event_groups():
        lines += [f"## {title}", ""]
        for member in members:
            lines.append(f"- `{member.value}` — {_payload_fields(PAYLOADS[member])}")
        lines.append("")
    lines += [
        "## Published but never stored",
        "",
        "`EPHEMERAL` in `athanore/events/names.py`:",
        "",
    ]
    for name in sorted(member.value for member in EPHEMERAL):
        lines.append(f"- `{name}`")
    return _document(lines)


# --------------------------------------------------------------------------
# skills/athanore-plugins/reference
# --------------------------------------------------------------------------


def _declarations() -> str:
    """The four declarations, the two enums, and the two closed vocabularies."""

    lines = [
        "# Plugin declarations",
        "",
        "The dataclasses a `@wf.route`, `@wf.action`, `wf.panel(...)` and",
        "`@wf.on(...)` produce, read off `athanore/plugins/decl.py`. What each",
        "one means is `docs/v1/09-plugins.md` §Declarations; the decorators",
        "that build them are `athanore/workflow.py`.",
        "",
    ]
    for cls in (decl.Route, decl.Action, decl.Panel, decl.Handler):
        lines += [f"## `{cls.__name__}`", ""]
        for name, annotation, default in _dataclass_fields(cls):
            lines.append(_declaration(name, annotation, default))
        lines.append("")
    lines += [
        "## `Slot` (and `Scope`, which is the same enum)",
        "",
        "Where a panel is shown, and what a declaration needs resolved before",
        "it runs: `docs/v1/09-plugins.md` §Slots, and",
        "`docs/v1/09-plugins.md` §Context and scopes.",
        "",
        *_members(decl.Slot),
        "",
        "## `PanelKind`",
        "",
        "The renderer vocabulary of",
        "`docs/v1/09-plugins.md` §Panel kinds (the renderer vocabulary), which",
        "fixes the shape a panel's `source` must return.",
        "",
        *_members(decl.PanelKind),
        "",
        "## `Placement`",
        "",
        *[f"- `{value}`" for value in sorted(decl.PLACEMENTS)],
        "",
        "## Methods a route may declare",
        "",
        *[f"- `{method}`" for method in sorted(decl.METHODS)],
        "",
        "## `PluginError`",
        "",
        f"- `{decl.PluginError.__name__}{_signature(decl.PluginError)}`",
        f"  - {_summary(decl.PluginError)}",
    ]
    return _document(lines)


def _service_classes() -> list[tuple[str, type]]:
    """The class behind each property of `PluginServices`, in declaration order.

    Resolved through the module the properties are annotated in, because
    the annotation is a string under PEP 563 and the point of this file is
    the *methods* the class has.
    """

    namespace = vars(inspect.getmodule(PluginServices))
    out: list[tuple[str, type] | None] = []
    for name, member in vars(PluginServices).items():
        if name.startswith("_") or not isinstance(member, property):
            continue
        assert member.fget is not None
        annotation = inspect.signature(member.fget).return_annotation
        target = namespace.get(annotation) if isinstance(annotation, str) else None
        out.append((name, target) if isinstance(target, type) else None)
    resolved = [entry for entry in out if entry is not None]
    if len(resolved) != len(out):
        raise RuntimeError(
            "a service property of athanore/plugins/context.py has a return "
            "annotation this script could not resolve to a class"
        )
    return resolved


def _context() -> str:
    """What a handler is handed: the context, its services, and the refusals."""

    lines = [
        "# `PluginContext`",
        "",
        "The one argument every plugin handler takes, read off",
        "`athanore/plugins/context.py`. Which of these a handler may reach",
        "for depends on the scope it was resolved in:",
        "`docs/v1/09-plugins.md` §Context and scopes.",
        "",
        "## Attributes",
        "",
    ]
    for name, annotation, default in _dataclass_fields(PluginContext):
        lines.append(_declaration(name, annotation, default))
    lines += [
        "",
        "## `ctx.ops`",
        "",
        f"- {_summary(PluginContext.ops.fget)}",
        "",
        *_methods(Ops, title="### `Ops`"),
        "## `ctx.services`",
        "",
        "Each is a property, so reaching for one out of scope raises where it",
        "is reached for.",
        "",
    ]
    services = _service_classes()
    for name, target in services:
        member = getattr(PluginServices, name)
        lines.append(f"- `ctx.services.{name}` → `{target.__name__}`")
        summary = _first_line(member.__doc__)
        if summary:
            lines.append(f"  - {summary}")
    lines.append("")
    for _, target in services:
        lines += _methods(target, title=f"### `{target.__name__}`")
    lines += [
        "## Refusals",
        "",
        "What the context itself raises when a handler reaches for something",
        "its scope does not have. Both are `PluginError(400, ...)`; an",
        "out-of-scope id is a 404 and never a 403",
        "(`docs/v1/09-plugins.md` §Context and scopes).",
        "",
        f"- `{NO_RUN}`",
        f"- `{NO_TASK}`",
    ]
    return _document(lines)


# --------------------------------------------------------------------------
# skills/athanore-api/reference
# --------------------------------------------------------------------------


def _credential(operation: dict[str, Any]) -> str:
    """The security scheme an operation declares, as one word."""

    security = operation.get("security")
    if not security:
        return "none"
    return ", ".join(sorted(scheme for entry in security for scheme in entry))


def _routes() -> str:
    """One row per operation of the committed OpenAPI snapshot.

    Read from `tests/snapshots/openapi.json` rather than from
    `create_app()`, so that a stale snapshot fails one check — the
    OpenAPI one — instead of two, and so this script never builds an
    application.
    """

    snapshot = json.loads(
        (ROOT / "tests" / "snapshots" / "openapi.json").read_text(encoding="utf-8")
    )
    lines = [
        "# The route table",
        "",
        "Every operation of `tests/snapshots/openapi.json`, the wire contract",
        "of `docs/v1/08-api.md` §Endpoints, generated from the code. The",
        "credential column is what the operation declares:",
        "`docs/v1/08-api.md` §Authentication (12 has the model).",
        "",
        "| Method | Path | Tag | Operation | Credential | Summary |",
        "|---|---|---|---|---|---|",
    ]
    rows: list[tuple[str, str, str, str, str, str]] = []
    for path, item in snapshot["paths"].items():
        for method, operation in item.items():
            rows.append(
                (
                    path,
                    method.upper(),
                    ", ".join(operation.get("tags", ())),
                    operation.get("operationId", ""),
                    _credential(operation),
                    operation.get("summary", ""),
                )
            )
    for path, method, tags, operation_id, credential, summary in sorted(rows):
        lines.append(
            f"| `{method}` | `{path}` | {tags} | `{operation_id}` "
            f"| {credential} | {summary} |"
        )
    return _document(lines)


def _error_codes() -> str:
    """The `code` vocabulary of the error shape, in declaration order."""

    lines = [
        "# Error codes",
        "",
        "The stable `code` of an error body, read off",
        "`athanore/api/errors.py`. The shape it appears in and what each one",
        "means is `docs/v1/08-api.md` §Conventions.",
        "",
        *[f"- `{member.value}`" for member in ErrorCode],
    ]
    return _document(lines)


# --------------------------------------------------------------------------
# skills/athanore-cli/reference
# --------------------------------------------------------------------------


def _parameter(parameter: Any) -> str | None:
    """One click parameter as a bullet, or ``None`` for a hidden one."""

    if getattr(parameter, "hidden", False):
        return None
    if parameter.param_type_name == "argument":
        label = parameter.metavar or str(parameter.name).upper()
        head = f"- `{label}`"
    else:
        head = "- " + ", ".join(f"`{opt}`" for opt in sorted(parameter.opts))
        if parameter.metavar:
            head += f" `{parameter.metavar}`"
    if parameter.required:
        head += " (required)"
    elif parameter.default is not None and parameter.default is not False:
        head += f" (default: `{parameter.default!r}`)"
    help_text = _first_line(getattr(parameter, "help", None))
    if help_text:
        head += f" — {help_text}"
    return head


def _command(command: Any, path: str, level: int) -> list[str]:
    """A heading, the help, the parameters, then every subcommand."""

    lines = [f"{'#' * level} `{path}`", ""]
    summary = _first_line(command.help or command.short_help)
    if summary:
        lines += [summary, ""]
    rendered = [
        bullet for bullet in map(_parameter, command.params) if bullet is not None
    ]
    if rendered:
        lines += [*rendered, ""]
    for name in sorted(getattr(command, "commands", {})):
        lines += _command(command.commands[name], f"{path} {name}", level + 1)
    return lines


def _commands() -> str:
    """The command tree, walked through click."""

    root: Any = get_command(cli_app)
    lines = [
        "# The command tree",
        "",
        "`athanore`, as `athanore/cli/__init__.py` and the verb modules",
        "beside it build it. What each verb is for is",
        "`docs/v1/11-cli.md` §Verbs; how a verb reaches a server is",
        "`docs/v1/11-cli.md` §Client connection; what it exits with is",
        "`docs/v1/11-cli.md` §Exit codes.",
        "",
        *_command(root, "athanore", 2),
    ]
    return _document(lines)


# --------------------------------------------------------------------------
# The targets
# --------------------------------------------------------------------------

#: Every file this script owns, checkout-relative, and what renders it.
#: `tests/test_skills.py` reads this table: a file under a `reference/`
#: directory that is not in it is an orphan, and one in it that is not on
#: disk is missing.
TARGETS: dict[str, Callable[[], str]] = {
    "skills/athanore-workflows/reference/public-api.md": _public_api,
    "skills/athanore-workflows/reference/node-options.md": _node_options,
    "skills/athanore-workflows/reference/agents.md": _agents,
    "skills/athanore-workflows/reference/events.md": _events,
    "skills/athanore-plugins/reference/declarations.md": _declarations,
    "skills/athanore-plugins/reference/context.md": _context,
    "skills/athanore-api/reference/routes.md": _routes,
    "skills/athanore-api/reference/error-codes.md": _error_codes,
    "skills/athanore-cli/reference/commands.md": _commands,
}


def render(target: str) -> str:
    """The exact text of one generated file, as it stands."""

    try:
        renderer = TARGETS[target]
    except KeyError:
        raise KeyError(f"{target} is not a file scripts/gen_skills.py writes") from None
    return renderer()


def main() -> None:
    for target in TARGETS:
        path = ROOT / target
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(target), encoding="utf-8")
        print(f"wrote {target}")


if __name__ == "__main__":
    main()
